# Generated by Django 4.2.3 on 2023-07-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbanner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
