# Generated by Django 4.2.3 on 2023-08-12 15:59

import app.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_topbanner_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Careers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("job_role", models.TextField()),
                ("image", models.ImageField(upload_to=app.models.image_path_rename)),
                ("is_full_time_role", models.BooleanField(default=False)),
                ("is_remote_role", models.BooleanField(default=False)),
                ("created_at", models.DateField()),
                ("requirements", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
            ],
            managers=[
                ("active_career", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=50)),
                ("designation", models.CharField(max_length=100)),
                ("company", models.CharField(blank=True, max_length=100, null=True)),
                ("other", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TopPacks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="topbanner",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="topbanner",
            name="image",
            field=models.ImageField(upload_to=app.models.image_path_rename),
        ),
    ]
