# Generated by Django 4.2.3 on 2023-08-24 19:12

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_toppacks_managers_toppacks_date_added_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="testimonial",
            managers=[
                ("active_testimonial", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="testimonial",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
