# Generated by Django 4.2.3 on 2023-08-24 20:06

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_testimonial_managers_testimonial_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careers",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=app.models.image_path_rename
            ),
        ),
    ]
