# Generated by Django 4.2.3 on 2023-08-25 18:02

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_careers_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to=app.models.image_path_rename)),
            ],
            options={
                "verbose_name_plural": "AboutBanner",
            },
        ),
    ]
