# Generated by Django 4.2.3 on 2023-08-26 17:16

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_aboutbanner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topbanner",
            name="image",
        ),
        migrations.CreateModel(
            name="TopBannerImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_by_title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to=app.models.image_path_rename)),
                (
                    "Banner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="app.topbanner",
                    ),
                ),
            ],
        ),
    ]
