# Generated by Django 4.2.3 on 2023-09-02 11:59

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_toppacks_image_by_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutbanner",
            options={"verbose_name_plural": "About Banner"},
        ),
        migrations.AlterModelOptions(
            name="careerbanner",
            options={"verbose_name_plural": "Career Banner"},
        ),
        migrations.AlterModelOptions(
            name="careers",
            options={"verbose_name_plural": "Careers"},
        ),
        migrations.AlterModelOptions(
            name="testimonial",
            options={"verbose_name_plural": "Testimonial"},
        ),
        migrations.AlterModelOptions(
            name="topbanner",
            options={"verbose_name_plural": "Top Banner"},
        ),
        migrations.AlterModelOptions(
            name="toppacks",
            options={"verbose_name_plural": "Top Packs"},
        ),
        migrations.AddField(
            model_name="topbanner",
            name="image",
            field=models.ImageField(default="", upload_to=app.models.image_path_rename),
        ),
        migrations.DeleteModel(
            name="TopBannerImages",
        ),
    ]
