# Generated by Django 4.2.3 on 2023-09-02 13:38

import app.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_alter_aboutbanner_options_alter_careerbanner_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutAsserts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=app.models.image_path_rename)),
                ("assert_detail", models.TextField(blank=True, null=True)),
                (
                    "assert_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Portfolio",
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200)),
                ("answer", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "FAQ",
            },
            managers=[
                ("active_faq", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="PortFolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=app.models.image_path_rename)),
                ("portfolio_detail", models.TextField(blank=True, null=True)),
                (
                    "portfolio_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Portfolio",
            },
            managers=[
                ("active_portfolio", django.db.models.manager.Manager()),
            ],
        ),
    ]
