# Generated by Django 4.2.3 on 2023-09-03 16:14

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_aboutasserts_faq_portfolio"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhyChoseUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=app.models.image_path_rename)),
                ("description", models.TextField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name_plural": "Why Chose Us",
            },
        ),
        migrations.AlterModelOptions(
            name="aboutasserts",
            options={"verbose_name_plural": "About Asserts"},
        ),
        migrations.RenameField(
            model_name="testimonial",
            old_name="other",
            new_name="description",
        ),
    ]
