# Generated by Django 4.2.3 on 2023-09-05 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_alter_testimonial_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="toppacks",
            old_name="add_image",
            new_name="image",
        ),
    ]
