# Generated by Django 4.2.3 on 2023-09-16 13:01

import app.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_rename_add_image_toppacks_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to=app.models.image_path_rename)),
            ],
            options={
                "verbose_name_plural": "Contact Banner",
            },
        ),
        migrations.CreateModel(
            name="ContactEmails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Contact Emails",
            },
            managers=[
                ("active_emails", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="portfolio",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="is_active",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="tag",
            field=models.CharField(
                choices=[
                    ("all", "all"),
                    ("ui/ux", "ui/ux"),
                    ("game development", "game development"),
                ],
                default="all",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="toppacks",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
